In [6]:
#IMPORTA O NUMPY
import numpy as np

'1.23.5'

Verifica a verssao do np.__version__

In [9]:
vetor = np.array([1,2,3,4,5,6,7,8,9,0,])


[1 2 3 4 5 6 7 8 9 0]


In [10]:
type(vetor)


numpy.ndarray

In [11]:
print(vetor)

[1 2 3 4 5 6 7 8 9 0]


In [12]:
vetor.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 45])

In [14]:
#
# 
vetor1 = np.arange(0,100, 3)
print(vetor1)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
matriz = np.matrix()

In [17]:
import pandas as pd
pd.__version__

'1.5.2'

In [23]:
from pandas import Series


obj = Series([1,2,3,4], index=["a","b","c","d"])
print(obj)

a    1
b    2
c    3
d    4
dtype: int64


In [30]:
import matplotlib.pyplot
matplotlib.__version__
%matplotlib inline

In [47]:
estudantes = {"Pedro":24, "Fernando":22, "Tania":26, "Cris":25}
len(estudantes)

4